package com.twitterintegration;

import java.awt.BorderLayout;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;

import javax.imageio.ImageIO;
import javax.servlet.ServletException;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

import twitter4j.Twitter;
import twitter4j.TwitterException;
import twitter4j.TwitterFactory;
import twitter4j.User;
import twitter4j.auth.AccessToken;
import twitter4j.conf.Configuration;
import twitter4j.conf.ConfigurationBuilder;

public class TwitterIntegrationServlet extends HttpServlet {
	
	private static final String ACCESS_TOKEN = "2291204155-74hZw6tJATnOnGidwlLvMLMCuoI0hv1gHveRaab";
	private static final String ACCESS_TOKEN_SECRET = "4NL4979d3FQNTIzhsmsorkQ0MzaMhcUi4T9HeNTZhGFvS";
	
	private static final String CONSUMER_KEY = "hHKbEpoT86DcFwuvZ0B8JQ";
	private static final String CONSUMER_SECRET = "J2LhRTHWlVcVta7E7BFGvZNy0h6ZVcZGFf5d97R0ERI";
	
	private static final String REQUEST_PARAMETER = "twitterHandle";
	
	private String twitterHandle;	
	private String profileImageURL;

	@Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        
        setTwitterHandle(request.getParameter(REQUEST_PARAMETER));
        
        try {
        	twitterImplementation();
        	
        } catch (TwitterException error) {
        	
        	// TODO Autogenerated catch block
        	error.printStackTrace();
        }
        
        ServletOutputStream output = response.getOutputStream();
        
        URL url = new URL(getProfileImageURL());
        
        Image image = ImageIO.read(url);
        
        JFrame frame = new JFrame();
        JLabel label = new JLabel(new ImageIcon(image));
        frame.getContentPane().add(label, BorderLayout.CENTER);
        frame.pack();
        frame.setVisible(true);
        
        // output.write(image);       
        
        /* URLConnection urlConnection = url.openConnection();
        BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(urlConnection.getInputStream())); */
        
        /* while (bufferedReader.read() != null) {
        	
        	output.write();        	
        } */
        
        // output.write(getProfileImageURL().getBytes());
        
        output.flush();
        output.close();
    }
	
	private void twitterImplementation() throws TwitterException {
		
		ConfigurationBuilder configurationBuilder = new ConfigurationBuilder();
		configurationBuilder.setOAuthConsumerKey(CONSUMER_KEY);
		configurationBuilder.setOAuthConsumerSecret(CONSUMER_SECRET);
		
		Configuration configuration = configurationBuilder.build();
		
		TwitterFactory twitterFactory = new TwitterFactory(configuration);
		Twitter twitter = twitterFactory.getInstance();
		
		AccessToken accessToken = new AccessToken(ACCESS_TOKEN, ACCESS_TOKEN_SECRET);
		
		twitter.setOAuthAccessToken(accessToken);
		
		User user = twitter.showUser(twitterHandle);
		
		this.profileImageURL = user.getOriginalProfileImageURL();
	}
	
	public String getProfileImageURL() { return this.profileImageURL; }
	
	public void setTwitterHandle(String twitterHandle) { this.twitterHandle = twitterHandle; }    
}